export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const AUTHENTICATION_LOGOFF = 'AUTHENTICATION_LOGOFF';
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
