export const RECEIVE_UPLOADED_IMAGES = 'RECEIVE_UPLOADED_IMAGES';
export const REMOVE_UPLOADED_IMAGE = 'REMOVE_UPLOADED_IMAGE';
export const RESET_UPLOADED_IMAGES = 'RESET_UPLOADED_IMAGES';
export const SET_IMAGES = 'SET_IMAGES';
